name: Update Donate

on:
  # 每当 push 到 main 分支时触发部署
  push:
    paths:
      - "LuckyTool/donate.json"
  # 手动触发部署
  workflow_dispatch:

# defaults:
#   run:
#     working-directory: website

jobs:
  update-donate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          # 选择要使用的 node 版本
          node-version: 20
          # 缓存 pnpm 依赖
      #          cache: pnpm

      - name: Get commit date
        id: date
        run: echo "time=$(git log -1 --pretty=format:"%ci" | sed 's/ //g; s/-//g; s/://g;' | cut -b 1-12)" >> $GITHUB_OUTPUT

      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.ACCESS_TOKEN }}"
          automatic_release_tag: "luckytool_donates"
          prerelease: false
          title: "${{ steps.date.outputs.time }}"
